// OTOMATİK ÜRETİLDİ — tools/gen-alarm-sounds.py. Elle düzenleme.
// Sentetik başlangıç alarm tonları; lisanslı paketlerle değiştirilebilir.
export interface AlarmSound {
  id: string;
  name: string;
  category: string;
  file: string;
}

export const ALARM_SOUNDS: AlarmSound[] = [
  { id: "alarm-001", name: "Klasik 01", category: "Klasik", file: "alarm-001.wav" },
  { id: "alarm-002", name: "Klasik 02", category: "Klasik", file: "alarm-002.wav" },
  { id: "alarm-003", name: "Klasik 03", category: "Klasik", file: "alarm-003.wav" },
  { id: "alarm-004", name: "Klasik 04", category: "Klasik", file: "alarm-004.wav" },
  { id: "alarm-005", name: "Klasik 05", category: "Klasik", file: "alarm-005.wav" },
  { id: "alarm-006", name: "Klasik 06", category: "Klasik", file: "alarm-006.wav" },
  { id: "alarm-007", name: "Klasik 07", category: "Klasik", file: "alarm-007.wav" },
  { id: "alarm-008", name: "Klasik 08", category: "Klasik", file: "alarm-008.wav" },
  { id: "alarm-009", name: "Klasik 09", category: "Klasik", file: "alarm-009.wav" },
  { id: "alarm-010", name: "Klasik 10", category: "Klasik", file: "alarm-010.wav" },
  { id: "alarm-011", name: "Klasik 11", category: "Klasik", file: "alarm-011.wav" },
  { id: "alarm-012", name: "Klasik 12", category: "Klasik", file: "alarm-012.wav" },
  { id: "alarm-013", name: "Klasik 13", category: "Klasik", file: "alarm-013.wav" },
  { id: "alarm-014", name: "Klasik 14", category: "Klasik", file: "alarm-014.wav" },
  { id: "alarm-015", name: "Klasik 15", category: "Klasik", file: "alarm-015.wav" },
  { id: "alarm-016", name: "Klasik 16", category: "Klasik", file: "alarm-016.wav" },
  { id: "alarm-017", name: "Dijital 01", category: "Dijital", file: "alarm-017.wav" },
  { id: "alarm-018", name: "Dijital 02", category: "Dijital", file: "alarm-018.wav" },
  { id: "alarm-019", name: "Dijital 03", category: "Dijital", file: "alarm-019.wav" },
  { id: "alarm-020", name: "Dijital 04", category: "Dijital", file: "alarm-020.wav" },
  { id: "alarm-021", name: "Dijital 05", category: "Dijital", file: "alarm-021.wav" },
  { id: "alarm-022", name: "Dijital 06", category: "Dijital", file: "alarm-022.wav" },
  { id: "alarm-023", name: "Dijital 07", category: "Dijital", file: "alarm-023.wav" },
  { id: "alarm-024", name: "Dijital 08", category: "Dijital", file: "alarm-024.wav" },
  { id: "alarm-025", name: "Dijital 09", category: "Dijital", file: "alarm-025.wav" },
  { id: "alarm-026", name: "Dijital 10", category: "Dijital", file: "alarm-026.wav" },
  { id: "alarm-027", name: "Dijital 11", category: "Dijital", file: "alarm-027.wav" },
  { id: "alarm-028", name: "Dijital 12", category: "Dijital", file: "alarm-028.wav" },
  { id: "alarm-029", name: "Dijital 13", category: "Dijital", file: "alarm-029.wav" },
  { id: "alarm-030", name: "Dijital 14", category: "Dijital", file: "alarm-030.wav" },
  { id: "alarm-031", name: "Dijital 15", category: "Dijital", file: "alarm-031.wav" },
  { id: "alarm-032", name: "Dijital 16", category: "Dijital", file: "alarm-032.wav" },
  { id: "alarm-033", name: "Yükselen 01", category: "Yükselen", file: "alarm-033.wav" },
  { id: "alarm-034", name: "Yükselen 02", category: "Yükselen", file: "alarm-034.wav" },
  { id: "alarm-035", name: "Yükselen 03", category: "Yükselen", file: "alarm-035.wav" },
  { id: "alarm-036", name: "Yükselen 04", category: "Yükselen", file: "alarm-036.wav" },
  { id: "alarm-037", name: "Yükselen 05", category: "Yükselen", file: "alarm-037.wav" },
  { id: "alarm-038", name: "Yükselen 06", category: "Yükselen", file: "alarm-038.wav" },
  { id: "alarm-039", name: "Yükselen 07", category: "Yükselen", file: "alarm-039.wav" },
  { id: "alarm-040", name: "Yükselen 08", category: "Yükselen", file: "alarm-040.wav" },
  { id: "alarm-041", name: "Yükselen 09", category: "Yükselen", file: "alarm-041.wav" },
  { id: "alarm-042", name: "Yükselen 10", category: "Yükselen", file: "alarm-042.wav" },
  { id: "alarm-043", name: "Yükselen 11", category: "Yükselen", file: "alarm-043.wav" },
  { id: "alarm-044", name: "Yükselen 12", category: "Yükselen", file: "alarm-044.wav" },
  { id: "alarm-045", name: "Alçalan 01", category: "Alçalan", file: "alarm-045.wav" },
  { id: "alarm-046", name: "Alçalan 02", category: "Alçalan", file: "alarm-046.wav" },
  { id: "alarm-047", name: "Alçalan 03", category: "Alçalan", file: "alarm-047.wav" },
  { id: "alarm-048", name: "Alçalan 04", category: "Alçalan", file: "alarm-048.wav" },
  { id: "alarm-049", name: "Alçalan 05", category: "Alçalan", file: "alarm-049.wav" },
  { id: "alarm-050", name: "Alçalan 06", category: "Alçalan", file: "alarm-050.wav" },
  { id: "alarm-051", name: "Alçalan 07", category: "Alçalan", file: "alarm-051.wav" },
  { id: "alarm-052", name: "Alçalan 08", category: "Alçalan", file: "alarm-052.wav" },
  { id: "alarm-053", name: "Alçalan 09", category: "Alçalan", file: "alarm-053.wav" },
  { id: "alarm-054", name: "Alçalan 10", category: "Alçalan", file: "alarm-054.wav" },
  { id: "alarm-055", name: "Alçalan 11", category: "Alçalan", file: "alarm-055.wav" },
  { id: "alarm-056", name: "Alçalan 12", category: "Alçalan", file: "alarm-056.wav" },
  { id: "alarm-057", name: "Siren 01", category: "Siren", file: "alarm-057.wav" },
  { id: "alarm-058", name: "Siren 02", category: "Siren", file: "alarm-058.wav" },
  { id: "alarm-059", name: "Siren 03", category: "Siren", file: "alarm-059.wav" },
  { id: "alarm-060", name: "Siren 04", category: "Siren", file: "alarm-060.wav" },
  { id: "alarm-061", name: "Siren 05", category: "Siren", file: "alarm-061.wav" },
  { id: "alarm-062", name: "Siren 06", category: "Siren", file: "alarm-062.wav" },
  { id: "alarm-063", name: "Siren 07", category: "Siren", file: "alarm-063.wav" },
  { id: "alarm-064", name: "Siren 08", category: "Siren", file: "alarm-064.wav" },
  { id: "alarm-065", name: "Siren 09", category: "Siren", file: "alarm-065.wav" },
  { id: "alarm-066", name: "Siren 10", category: "Siren", file: "alarm-066.wav" },
  { id: "alarm-067", name: "Siren 11", category: "Siren", file: "alarm-067.wav" },
  { id: "alarm-068", name: "Siren 12", category: "Siren", file: "alarm-068.wav" },
  { id: "alarm-069", name: "Darbe 01", category: "Darbe", file: "alarm-069.wav" },
  { id: "alarm-070", name: "Darbe 02", category: "Darbe", file: "alarm-070.wav" },
  { id: "alarm-071", name: "Darbe 03", category: "Darbe", file: "alarm-071.wav" },
  { id: "alarm-072", name: "Darbe 04", category: "Darbe", file: "alarm-072.wav" },
  { id: "alarm-073", name: "Darbe 05", category: "Darbe", file: "alarm-073.wav" },
  { id: "alarm-074", name: "Darbe 06", category: "Darbe", file: "alarm-074.wav" },
  { id: "alarm-075", name: "Darbe 07", category: "Darbe", file: "alarm-075.wav" },
  { id: "alarm-076", name: "Darbe 08", category: "Darbe", file: "alarm-076.wav" },
  { id: "alarm-077", name: "Darbe 09", category: "Darbe", file: "alarm-077.wav" },
  { id: "alarm-078", name: "Darbe 10", category: "Darbe", file: "alarm-078.wav" },
  { id: "alarm-079", name: "Darbe 11", category: "Darbe", file: "alarm-079.wav" },
  { id: "alarm-080", name: "Darbe 12", category: "Darbe", file: "alarm-080.wav" },
  { id: "alarm-081", name: "Darbe 13", category: "Darbe", file: "alarm-081.wav" },
  { id: "alarm-082", name: "Darbe 14", category: "Darbe", file: "alarm-082.wav" },
  { id: "alarm-083", name: "Darbe 15", category: "Darbe", file: "alarm-083.wav" },
  { id: "alarm-084", name: "Darbe 16", category: "Darbe", file: "alarm-084.wav" },
  { id: "alarm-085", name: "Melodi 01", category: "Melodi", file: "alarm-085.wav" },
  { id: "alarm-086", name: "Melodi 02", category: "Melodi", file: "alarm-086.wav" },
  { id: "alarm-087", name: "Melodi 03", category: "Melodi", file: "alarm-087.wav" },
  { id: "alarm-088", name: "Melodi 04", category: "Melodi", file: "alarm-088.wav" },
  { id: "alarm-089", name: "Melodi 05", category: "Melodi", file: "alarm-089.wav" },
  { id: "alarm-090", name: "Melodi 06", category: "Melodi", file: "alarm-090.wav" },
  { id: "alarm-091", name: "Melodi 07", category: "Melodi", file: "alarm-091.wav" },
  { id: "alarm-092", name: "Melodi 08", category: "Melodi", file: "alarm-092.wav" },
  { id: "alarm-093", name: "Melodi 09", category: "Melodi", file: "alarm-093.wav" },
  { id: "alarm-094", name: "Melodi 10", category: "Melodi", file: "alarm-094.wav" },
  { id: "alarm-095", name: "Melodi 11", category: "Melodi", file: "alarm-095.wav" },
  { id: "alarm-096", name: "Melodi 12", category: "Melodi", file: "alarm-096.wav" },
  { id: "alarm-097", name: "Melodi 13", category: "Melodi", file: "alarm-097.wav" },
  { id: "alarm-098", name: "Melodi 14", category: "Melodi", file: "alarm-098.wav" },
  { id: "alarm-099", name: "Melodi 15", category: "Melodi", file: "alarm-099.wav" },
  { id: "alarm-100", name: "Melodi 16", category: "Melodi", file: "alarm-100.wav" },
];

export const DEFAULT_ALARM_SOUND_ID = "alarm-001";
export const ALARM_CATEGORIES = [
  "Klasik",
  "Dijital",
  "Yükselen",
  "Alçalan",
  "Siren",
  "Darbe",
  "Melodi",
] as const;
